import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppProvider } from "@/store/global/global.provider";
import "@fortawesome/fontawesome-svg-core/styles.css";
import ReactQueryProviders from "./libs/react-query-providers";
import NavbarComponent from "@/components/Navbar";
import FooterComponent from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/animate.css@4.0.0/animate.min.css"
        />
      </head>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <ReactQueryProviders>
            <AppProvider>
              <NavbarComponent />
              <section className="container">
                {children}
              </section>
              <FooterComponent />
            </AppProvider>
          </ReactQueryProviders>
        </body>
      </html>
    </>
  );
}
